### ISSUE TITLE
how to set gas price and gas limit for a trade ?

### ISSUE THREAD

**Issue by tanpv** [shanefontaine/uniswap-python#34] opened 2020-09-30 08:08 UTC
hi, using uniswap-python lib, Could I set the gas price and gas limit for the trade ?
seem I do not find this from readme document, please help

also have same question with slip page setting.
Do we support this in near future ?

**Comment by ErikBjare** [comment] 2020-09-30 10:42
Duplicate of https://github.com/shanefontaine/uniswap-python/issues/23.

You need to pass in a custom Web3 instance to the constructor, with the gas strategy that you want. See the Web3 docs for how to do that: https://web3py.readthedocs.io/en/stable/gas_price.html

>also have same question with slippage setting.

There's a constructor parameter for that as well: https://github.com/shanefontaine/uniswap-python/blob/672ce87c9f330a20bb5f17742d65eafbaf484e80/uniswap/uniswap.py#L132

**Closed by ErikBjare** 2020-09-30 10:42 UTC

**Comment by tanpv** [comment] 2020-09-30 14:22
many thanks @ErikBjare

**Comment by stamatelou** [comment] 2021-03-15 19:46
@ErikBjare were you able to pass the instance to the constructor? And if yes, in which part of the uniswap.py script you added the instance from web3 ?

**Comment by albertocastillo2001** [comment] 2021-03-30 11:38
@ErikBjare Could you please provide an example on this
I've been taking a look at the uniswap.py class, but I cannot seem to figure out how you would pass that w3 parameter in the constructor and what you would need to put there.

something like this doesn't work
`uniswap_wrapper = Uniswap(address=eth_address, private_key=eth_priv_key, provider=eth_infura_node, web3=web3.gas_strategies.time_based.fast_gas_price_strategy)`

**Comment by ErikBjare** [comment] 2021-03-30 11:46
You need to pass a Web3 object, not a gas strategy object. Read the Web3 docs: 

 - https://web3py.readthedocs.io/en/stable/quickstart.html
 - https://web3py.readthedocs.io/en/stable/providers.html

The `provider` and `web3` parameters are mutually exclusive. Specifically, see the first lines of `Uniswap.__init__`:
https://github.com/shanefontaine/uniswap-python/blob/5ec7a1c5c6d861f90d935ab5faf680d2ab3aa112/uniswap/uniswap.py#L143-L150

**Comment by albertocastillo2001** [comment] 2021-03-30 18:38
Hello @ErikBjare

Thanks a lot. Correct. WHat I did was creating a w3 instance like this:

`w3 = Web3(Web3.HTTPProvider(eth_infura_node, request_kwargs={"timeout": 60}))
w3.eth.setGasPriceStrategy(fast_gas_price_strategy)`

Then pass it through the w3 argument of the Uniswap constructor class. Seems it worked. But would you add this as a parameter on the class where we can specify the gwei directly? I think it's much easier.

**Comment by albertocastillo2001** [comment] 2021-03-30 22:57
Thank you

**Comment by Weizilla** [comment] 2021-04-06 14:20
@ErikBjare How do you set the gas **limit**, not price? The price can be overwritten by `w3.eth.setGasPriceStrategy` as you pointed out but the limit always defaults to `250000` here: https://github.com/shanefontaine/uniswap-python/blob/master/uniswap/uniswap.py#L768

**Comment by Weizilla** [comment] 2021-04-06 15:26
I'm happy to make a PR for overwriting the default gas limit if you have a preference for how it should be passed in. Such as in the constructor or with each individual `make_trade` call or by some other means.

**Comment by Marsh-James** [comment] 2021-08-13 17:07
> I'm happy to make a PR for overwriting the default gas limit if you have a preference for how it should be passed in. Such as in the constructor or with each individual `make_trade` call or by some other means.

@Weizilla Makes an interesting point, any thoughts @ErikBjare? Was there a particular rationale behind this?

**Comment by troublesprouter** [comment] 2024-04-01 22:04
Was a simple and quick way to make the transaction very fast found? I'm finding that using a custom web3 makes the process much slower, defeating the process of making the transaction faster.
