### ISSUE TITLE
Code requires address and private key

### ISSUE THREAD

**Issue by alex33d** [shanefontaine/uniswap-python#18] opened 2020-08-15 07:37 UTC
Hi
Executing the following command results in TypeError: __init__() missing 2 required positional arguments: 'address' and 'private_key'

```
from uniswap import Uniswap
uniswap_wrapper = Uniswap()
eth = "0x0000000000000000000000000000000000000000"
bat = "0x0D8775F648430679A709E98d2b0Cb6250d2887EF"
dai = "0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359"

uniswap_wrapper.get_eth_balance(bat)
```

Could not find the clarification on how to set the address/private key in ReadMe file... Would appreciate help on the issue.
Thanks!

**Comment by ErikBjare** [comment] 2020-09-25 17:52
@alex33d No, that is not possible. For that, you'd need an archive node to parse the event logs, which is way beyond the scope of this library.

Duplicate of https://github.com/shanefontaine/uniswap-python/issues/16, closing.

**Closed by ErikBjare** 2020-09-25 17:52 UTC

**Comment by ErikBjare** [comment] 2020-09-25 19:46
This is now mentioned in the README: https://github.com/shanefontaine/uniswap-python/commit/b5f21fcbb18a537bf99a044e84c4b7fa31938fe7
